class Settings:
    SEARCH_ANGLE_RANGE = 40
    ATTACK_ANGLE_RANGE = 30

    REGEN_HP_THRESHOLD = 80
    REGEN_POWER_THRESHOLD = 60

    HEAL_IN_COMBAT_THRESHOLD = 30

    LOOTING_RANGE = 4

    HIGHER_LEVEL_MOB_THRESHOLD = 2
    LOWER_LEVEL_MOB_THRESHOLD = 4

    SEARCH_RANGE = 20

    MIN_ACTION_DELAY_SECONDS = 0.3
    LOOT_ACTION_DELAY_SECONDS = 2
    LOOT_ACTION_REPEAT_SECONDS = 3

    MOB_GROUP_PROXIMITY_RANGE = 20  # range between mobs to consider them a group

    REPORTING_TIME = 10
